packages:
  - packages/**
  - examples/**

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true

minimumReleaseAge: 1440

catalog:
  "@types/node": "^25.9.1"
  tsdown: "^0.22.1"
  vite: "^8.0.14"
  vitest: "^4.1.7"

allowBuilds:
  "@swc/core": true
  esbuild: true
